---
- name: Setup test ec2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create test ec2 instance
      ec2:
        key_name: MyTestKeyOhio
        region: us-east-2
        instance_type: t2.micro
        image: ami-0c7f9161f8491665f
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "test-instance"
          Project: Testing
          Owner: DevOps Testing
        exact_count: 1
        count_tag:
          Name: "test-instance"
          Project: Testing
          Owner: DevOps Testing
