---
- name: Setup test ec2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create test ec2 instance
      ec2_instance:
        name: "test-instance"
        key_name: "MyTestKeyOhio"
        instance_type: t2.micro
        security_group: ansible-sg
        image_id: ami-0c7f9161f8491665f
        region: us-east-2
        wait: yes
        wait_timeout: 300
        tags:
          Environment: Testing
